version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies..
      - echo `pwd`
      - echo Going to run cd
      - cd $(echo ${CODEBUILD_INITIATOR} | sed 's/-dev//g' | sed 's/-prod//g' | cut -d'/' -f2)
      - echo `pwd`
      - npm install -y npm@latest
      - npm install -g yarn
      - rm package-lock.json
      - yarn config set ignore-engines true
      - yarn add webpack-cli --dev
    pre_build:
      commands:
        - yarn install --non-interactive
  build:
    commands:
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: yes
  base-directory: $(echo ${CODEBUILD_INITIATOR} | sed 's/-dev//g' | sed 's/-prod//g' | cut -d'/' -f2)/dist
